name: khlive_streaming
description: KHLive Streaming
version: 0.0.1
environment:
  sdk: '>=1.24.0 <2.0.0'
dependencies:
  angular2: ^3.1.0
  angular_components: ^0.5.1
  firebase: ^3.0.0
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
web:
  compiler:
    debug: dartdevc
